import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import CommonLayout from "@/components/CommonLayout";

export const metadata = {
  title: "Personal Finance Visualizer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-screen h-screen overflow-hidden">
        <div className="w-full h-full">
          <CommonLayout>{children}</CommonLayout>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
